// Generated by gencpp from file er1_motor_driver/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ER1_MOTOR_DRIVER_MESSAGE_ADDTWOINTS_H
#define ER1_MOTOR_DRIVER_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <er1_motor_driver/AddTwoIntsRequest.h>
#include <er1_motor_driver/AddTwoIntsResponse.h>


namespace er1_motor_driver
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace er1_motor_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::er1_motor_driver::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::er1_motor_driver::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::er1_motor_driver::AddTwoInts > {
  static const char* value()
  {
    return "er1_motor_driver/AddTwoInts";
  }

  static const char* value(const ::er1_motor_driver::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::er1_motor_driver::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::er1_motor_driver::AddTwoInts > 
template<>
struct MD5Sum< ::er1_motor_driver::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::er1_motor_driver::AddTwoInts >::value();
  }
  static const char* value(const ::er1_motor_driver::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::er1_motor_driver::AddTwoIntsRequest> should match 
// service_traits::DataType< ::er1_motor_driver::AddTwoInts > 
template<>
struct DataType< ::er1_motor_driver::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::er1_motor_driver::AddTwoInts >::value();
  }
  static const char* value(const ::er1_motor_driver::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::er1_motor_driver::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::er1_motor_driver::AddTwoInts > 
template<>
struct MD5Sum< ::er1_motor_driver::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::er1_motor_driver::AddTwoInts >::value();
  }
  static const char* value(const ::er1_motor_driver::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::er1_motor_driver::AddTwoIntsResponse> should match 
// service_traits::DataType< ::er1_motor_driver::AddTwoInts > 
template<>
struct DataType< ::er1_motor_driver::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::er1_motor_driver::AddTwoInts >::value();
  }
  static const char* value(const ::er1_motor_driver::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ER1_MOTOR_DRIVER_MESSAGE_ADDTWOINTS_H
